import { FormEvent, useEffect, useState } from "react";
import { caseApi, type ContactDetails, type Incident, type IncidentCase, type IncidentField, type SafeUser } from "./api/cases";

type Page = "home" | "complaint" | "track" | "suspect" | "resources" | "faq" | "contact" | "policy" | "login" | "signup";
type Step = "type" | "story" | "verify" | "missing" | "evidence" | "contact" | "review" | "success";
type ContactDraft = { fullName: string; mobileNumber: string; email: string; otp: string };

const emptyContact: ContactDraft = { fullName: "", mobileNumber: "", email: "", otp: "" };
const labels: Record<IncidentField, string> = { incidentDate: "Date of incident", amountLost: "Amount lost (INR)", paymentApp: "Payment method or app", transactionId: "Transaction ID / UTR", recipientUpiId: "Recipient UPI ID" };
const fieldNames: (keyof Incident)[] = ["incidentDate", "incidentTime", "amountLost", "paymentApp", "transactionId", "recipientUpiId", "phoneNumber", "bankOrMerchant"];
const toDraft = (incident: Incident) => ({ ...incident, amountLost: incident.amountLost?.toString() ?? "", narrativeFacts: incident.narrativeFacts.join("\n") });
const fileToBase64 = (file: File) => new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result).split(",")[1]); reader.onerror = reject; reader.readAsDataURL(file); });

function PortalHeader({ page, user, go, logout }: { page: Page; user: SafeUser | null; go: (page: Page) => void; logout: () => void }) {
  const [hindi, setHindi] = useState(false);
  const nav = <><button className={page === "home" ? "nav-link active" : "nav-link"} onClick={() => go("home")}>Home</button><button className={page === "complaint" ? "nav-link active" : "nav-link"} onClick={() => go("complaint")}>Register a Complaint</button><button className={page === "track" ? "nav-link active" : "nav-link"} onClick={() => go("track")}>Track Complaint</button><button className={page === "resources" ? "nav-link active" : "nav-link"} onClick={() => go("resources")}>Prevent Cyber Crime</button><button className={page === "contact" ? "nav-link active" : "nav-link"} onClick={() => go("contact")}>Help &amp; Contact</button></>;
  return <><a className="skip-link" href="#main-content">Skip to main content</a><header className="portal-header"><div className="portal-header-inner"><button className="portal-brand" onClick={() => go("home")}><span className="portal-title">National Cyber Crime Reporting Portal</span><span className="portal-subtitle">Citizen Services</span></button><div className="portal-tools"><button className="text-button" onClick={() => go("policy")}>Accessibility &amp; help</button><select aria-label="Language" onChange={(event) => setHindi(event.target.value === "hi")} defaultValue="en"><option value="en">English</option><option value="hi">Hindi</option></select>{user ? <div className="account-area"><span>{user.name}</span><button className="text-button" onClick={() => go("home")}>My Complaints</button><button className="text-button" onClick={logout}>Logout</button></div> : <div className="auth-actions"><button className="text-button" onClick={() => go("login")}>Login</button><button className="text-button" onClick={() => go("signup")}>Sign Up</button></div>}</div></div>{hindi && <p className="language-message">हिंदी संस्करण इस प्रोटोटाइप में अभी उपलब्ध नहीं है।</p>}</header><nav className="portal-nav desktop-nav" aria-label="Primary navigation"><div className="portal-nav-inner">{nav}</div></nav><details className="mobile-nav"><summary>Menu</summary><nav aria-label="Primary navigation">{nav}</nav></details></>;
}

export function App() {
  const [page, setPage] = useState<Page>("home");
  const [step, setStep] = useState<Step>("type");
  const [caseData, setCaseData] = useState<IncidentCase | null>(null);
  const [story, setStory] = useState("");
  const [draft, setDraft] = useState<any>(null);
  const [answer, setAnswer] = useState("");
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);
  const [declaration, setDeclaration] = useState(false);
  const [missingHistory, setMissingHistory] = useState<IncidentField[]>([]);
  const [contactDraft, setContactDraft] = useState<ContactDraft>(emptyContact);
  const [user, setUser] = useState<SafeUser | null>(null);
  const [myCases, setMyCases] = useState<IncidentCase[]>([]);
  const [pendingClaimToken, setPendingClaimToken] = useState<string | null>(null);
  const [trackReference, setTrackReference] = useState("");

  const run = async (work: () => Promise<void>) => {
    setLoading(true); setError("");
    try { await work(); } catch (e) { setError(e instanceof Error ? e.message : "Something went wrong."); } finally { setLoading(false); }
  };
  const refreshMyCases = async (currentUser = user) => {
    if (!currentUser) return setMyCases([]);
    setMyCases(await caseApi.myCases());
  };

  useEffect(() => { void caseApi.me().then(({ user }) => setUser(user)).catch(() => setUser(null)); }, []);
  useEffect(() => { void refreshMyCases(); }, [user]);

  const begin = () => { setPage("complaint"); setStep("type"); setCaseData(null); setStory(""); setDraft(null); setAnswer(""); setMissingHistory([]); setContactDraft(emptyContact); setDeclaration(false); };
  const chooseFinancial = () => void run(async () => { const item = await caseApi.create(); setCaseData(item); setStep("story"); });
  const submitStory = (event: FormEvent) => { event.preventDefault(); if (!caseData || !story.trim()) return; void run(async () => { const item = await caseApi.saveStory(caseData.id, story.trim()); setCaseData(item); setDraft(toDraft(item.incident)); setStep("verify"); }); };
  const update = (key: string, value: string) => setDraft((current: any) => ({ ...current, [key]: value }));
  const verify = (event: FormEvent) => { event.preventDefault(); if (!caseData || !draft) return; void run(async () => { const { fraudType: _fraudType, currency: _currency, amountLost, narrativeFacts, ...updates } = draft; const item = await caseApi.updateIncident(caseData.id, { ...updates, amountLost: amountLost ? Number(amountLost) : null, narrativeFacts: narrativeFacts.split("\n").map((x: string) => x.trim()).filter(Boolean) }); const missing = await caseApi.getMissing(item.id); setMissingHistory([]); setCaseData(item); setStep(missing.nextQuestion ? "missing" : "evidence"); }); };
  const saveMissing = (skip = false) => { if (!caseData) return; void run(async () => { const field = caseData.missingFields[0]; if (!field) { setStep("evidence"); return; } const value: any = skip ? null : field === "amountLost" ? Number(answer) : answer.trim(); if (!skip && (!value || (field === "amountLost" && value <= 0))) throw new Error("Please enter a valid value or choose 'I don't have this information'."); const item = await caseApi.updateIncident(caseData.id, { [field]: value }); const remaining = item.missingFields.filter((entry) => entry !== field); setMissingHistory((current) => [...current, field]); setCaseData({ ...item, missingFields: remaining }); setAnswer(""); if (!remaining.length) setStep("evidence"); }); };
  const restoreMissingQuestion = () => { if (!caseData || !missingHistory.length) { setStep("verify"); return; } const previous = missingHistory[missingHistory.length - 1]; setMissingHistory((current) => current.slice(0, -1)); setCaseData((current) => current ? { ...current, missingFields: [previous, ...current.missingFields.filter((entry) => entry !== previous)] } : current); setAnswer(""); setStep("missing"); };
  const backFromEvidence = () => { if (!missingHistory.length) { setStep("verify"); return; } restoreMissingQuestion(); };
  const upload = async (files: FileList | null) => { const file = files?.[0]; if (!file || !caseData) return; if (!["image/png", "image/jpeg", "application/pdf"].includes(file.type)) { setError("Choose a PNG, JPEG, or PDF file."); return; } await run(async () => setCaseData(await caseApi.uploadEvidence(caseData.id, file.name, file.type as any, await fileToBase64(file)))); };
  const saveContact = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!caseData) return; const contact: ContactDetails = { fullName: contactDraft.fullName, mobileNumber: contactDraft.mobileNumber, email: contactDraft.email.trim() || null, otpVerified: contactDraft.otp === "123456" }; void run(async () => { if (!contact.otpVerified) throw new Error("Enter simulated OTP 123456 to continue."); setCaseData(await caseApi.saveContact(caseData.id, contact)); setStep("review"); }); };
  const submit = () => { if (!caseData || !declaration) { setError("Please confirm the declaration before submitting."); return; } void run(async () => { const item = await caseApi.submitMock(caseData.id); setCaseData(item); setPendingClaimToken(item.claimToken ?? null); if (user) await refreshMyCases(); setStep("success"); }); };
  const logout = () => void run(async () => { await caseApi.logout(); setUser(null); setMyCases([]); setPage("home"); });
  const completeAuth = async (nextUser: SafeUser) => { setUser(nextUser); if (pendingClaimToken) { await caseApi.claimCase(pendingClaimToken); setPendingClaimToken(null); } await refreshMyCases(nextUser); setPage("home"); };
  const openTrack = (reference: string) => { setTrackReference(reference); setPage("track"); };
  const go = (target: Page) => target === "complaint" ? begin() : setPage(target);

  return <div className="portal-shell"><PortalHeader page={page} user={user} go={go} logout={logout} /><main className="page-shell" id="main-content">{error && <div className="notice error" role="alert">{error}<button onClick={() => setError("")}>×</button></div>}{page === "home" && <Home go={go} user={user} myCases={myCases} openTrack={openTrack} />}{page === "complaint" && <Complaint step={step} setStep={setStep} caseData={caseData} story={story} setStory={setStory} draft={draft} update={update} chooseFinancial={chooseFinancial} submitStory={submitStory} verify={verify} answer={answer} setAnswer={setAnswer} saveMissing={saveMissing} backFromMissing={restoreMissingQuestion} backFromEvidence={backFromEvidence} upload={upload} remove={(id: string) => caseData && run(async () => setCaseData(await caseApi.removeEvidence(caseData.id, id)))} contactDraft={contactDraft} setContactDraft={setContactDraft} saveContact={saveContact} declaration={declaration} setDeclaration={setDeclaration} submit={submit} loading={loading} begin={begin} go={go} user={user} pendingClaimToken={pendingClaimToken} openTrack={openTrack} />}{page === "track" && <Track initialReference={trackReference} />}{page === "suspect" && <Suspect />}{page === "resources" && <Resources />}{page === "faq" && <Faq />}{page === "contact" && <Contact />}{page === "policy" && <Policies />}{page === "login" && <Login onLogin={completeAuth} go={go} />}{page === "signup" && <Signup onSignup={completeAuth} go={go} />}</main><footer className="portal-footer"><p>Independent hackathon prototype — not a government website.</p><p>All information and actions in this prototype must use synthetic data only.</p><p><button onClick={() => setPage("policy")}>Privacy Notice</button> · <button onClick={() => setPage("policy")}>Disclaimer</button> · <button onClick={() => setPage("policy")}>Website Policies</button></p></footer></div>;
}

function Home({ go, user, myCases, openTrack }: { go: (page: Page) => void; user: SafeUser | null; myCases: IncidentCase[]; openTrack: (reference: string) => void }) {
  return <section className="dashboard" aria-labelledby="dashboard-title"><div className="dashboard-hero"><p className="eyebrow">Citizen services</p><h1 id="dashboard-title">Report cybercrime online</h1><p>Use this guided prototype to prepare a synthetic UPI financial-fraud complaint draft. Review every detail before you continue.</p><div className="dashboard-actions"><button className="primary-button dashboard-primary" onClick={() => go("complaint")}>Register a Complaint</button><button className="secondary-button dashboard-secondary" onClick={() => go("track")}>Track Your Complaint</button></div></div>{user && <section className="information-section"><h2>My Complaints</h2>{myCases.length ? <div className="complaint-list">{myCases.map((item) => <article className="complaint-card" key={item.id}><strong>{item.mockSubmission?.reference ?? "Draft complaint"}</strong><span>UPI Financial Fraud</span><span>{item.mockSubmission?.submittedAt ? new Date(item.mockSubmission.submittedAt).toLocaleString() : "Draft"}</span><span>Status: {item.mockSubmission?.status ?? item.status}</span>{item.mockSubmission?.reference ? <button className="secondary-button" onClick={() => openTrack(item.mockSubmission!.reference)}>Track Complaint</button> : <button className="secondary-button" onClick={() => go("complaint")}>Continue</button>}</article>)}</div> : <div className="notice"><p>You have not submitted any complaints yet.</p><button className="primary-button dashboard-primary" onClick={() => go("complaint")}>Register a Complaint</button></div>}</section>}<div className="service-grid"><button className="service-card" onClick={() => go("resources")}><strong>Prevent Cyber Crime</strong><span>Simple steps to recognise and avoid common online fraud.</span></button><button className="service-card" onClick={() => go("complaint")}><strong>What you need before reporting</strong><span>Prepare the key details that help you describe the incident.</span></button><button className="service-card" onClick={() => go("contact")}><strong>Help &amp; Contact</strong><span>Find guidance and support information for this prototype.</span></button></div><section className="information-section"><h2>Keep these details ready</h2><ul><li>Transaction details</li><li>Screenshots</li><li>Dates and amounts</li><li>Communication records</li></ul></section><section className="help-section"><div><strong>General information</strong><p>This portal is an independent demonstration. Use only synthetic data and do not enter real personal or payment information.</p></div><div><strong>Urgent help</strong><p>If you believe you are experiencing an active financial fraud, contact your bank or payment provider immediately and use official support channels.</p></div></section></section>;
}

function Complaint(props: any) {
  const { step, setStep, caseData, story, setStory, draft, update, chooseFinancial, submitStory, verify, answer, setAnswer, saveMissing, backFromMissing, backFromEvidence, upload, remove, contactDraft, setContactDraft, saveContact, declaration, setDeclaration, submit, loading, begin, go, user, pendingClaimToken, openTrack } = props;
  if (step === "type") return <section className="journey-card screen"><p className="eyebrow">Register a complaint</p><h1>Choose complaint type</h1><p className="lead">This prototype fully supports the financial-fraud path.</p><div className="choice-grid"><button className="service-card" onClick={chooseFinancial}><strong>Financial Fraud</strong><span>UPI and payment-related fraud.</span></button><button className="service-card" onClick={() => alert("Other Cyber Crime is not implemented in this prototype.")}><strong>Other Cyber Crime</strong><span>Prototype limitation.</span></button><button className="service-card" onClick={() => alert("Women & Children Related Crime is not collected in this prototype. Please use the official portal.")}><strong>Women & Children Related Crime</strong><span>Use official reporting channels.</span></button></div></section>;
  if (!caseData) return null;
  if (step === "story") return <form className="journey-card screen" onSubmit={submitStory}><p className="eyebrow">Financial fraud · Step 1</p><h1>Tell us what happened</h1><p className="lead">Describe the incident in your own words. This prototype only organises details that you explicitly mention.</p><label className="field-label">Your story<textarea value={story} onChange={(e) => setStory(e.target.value)} rows={9} required placeholder="Example: I transferred ₹25,000 through UPI to demo-fraud@upi on 26 August 2026. My UTR is DEMO12345." /></label><p className="helper">Use synthetic information only. No AI is used in this prototype.</p><div className="dashboard-actions"><button className="secondary-button dashboard-secondary" type="button" onClick={() => go("home")}>Back to Home</button><button className="primary-button dashboard-primary" disabled={loading}>Continue</button></div></form>;
  if (step === "verify") return <form className="journey-card screen" onSubmit={verify}><p className="eyebrow">Step 2</p><h1>Here’s what we understood</h1><p className="notice"><strong>Not verified</strong> — please review or correct each value before you continue.</p><div className="field-grid">{fieldNames.map((key) => <label className="field-label" key={key}>{String(key).replace(/([A-Z])/g, " $1")}<input type={key === "incidentDate" ? "date" : key === "amountLost" ? "number" : key === "incidentTime" ? "time" : "text"} value={draft[key] ?? ""} onChange={(e) => update(key, e.target.value)} /></label>)}</div><label className="field-label">Description<textarea rows={4} value={draft.narrativeFacts} onChange={(e) => update("narrativeFacts", e.target.value)} /></label><div className="dashboard-actions"><button className="secondary-button dashboard-secondary" type="button" onClick={() => setStep("story")}>Back</button><button className="primary-button dashboard-primary" disabled={loading}>Confirm &amp; continue</button></div></form>;
  if (step === "missing") { const field = caseData.missingFields[0] as IncidentField; return <section className="journey-card screen"><p className="eyebrow">Step 3</p><h1>{labels[field]}</h1><p className="lead">Please provide this if you have it. You can continue without it.</p><label className="field-label">{labels[field]}<input type={field === "incidentDate" ? "date" : field === "amountLost" ? "number" : "text"} value={answer} onChange={(e) => setAnswer(e.target.value)} /></label><div className="dashboard-actions"><button className="secondary-button dashboard-secondary" type="button" onClick={backFromMissing}>Back</button><button className="primary-button dashboard-primary" onClick={() => saveMissing(false)} disabled={loading}>Save and continue</button><button className="secondary-button dashboard-secondary" onClick={() => saveMissing(true)} disabled={loading}>I don’t have this information</button></div></section>; }
  if (step === "evidence") return <section className="journey-card screen"><p className="eyebrow">Step 4</p><h1>Add evidence</h1><p className="lead">Evidence is optional. Images are shown as uploaded; PDFs show their file details. No OCR is performed.</p><label className="upload-box">Choose PNG, JPEG, or PDF<input className="visually-hidden" type="file" accept="image/png,image/jpeg,application/pdf" onChange={(e) => void upload(e.target.files)} /></label><ul className="file-list">{caseData.evidence.map((item: any) => <li className="evidence-list-item" key={item.id}>{item.mimeType.startsWith("image/") ? <img className="evidence-preview" src={item.storedPath} alt={`Uploaded evidence ${item.filename}`} /> : <span>PDF document</span>}<strong>{item.filename}</strong><small>{Math.ceil(item.size / 1024)} KB · {item.mimeType}</small><button className="action-button-small" onClick={() => remove(item.id)}>Remove</button></li>)}</ul><div className="dashboard-actions"><button className="secondary-button dashboard-secondary" type="button" onClick={backFromEvidence}>Back</button><button className="secondary-button dashboard-secondary" onClick={() => setStep("contact")}>Skip for now</button><button className="primary-button dashboard-primary" onClick={() => setStep("contact")}>Continue</button></div></section>;
  if (step === "contact") return <form className="journey-card screen" onSubmit={saveContact}><p className="eyebrow">Step 5</p><h1>Your contact details</h1><p className="notice">OTP verification is simulated in this prototype. Use <strong>123456</strong>.</p><div className="field-grid"><label className="field-label">Full name<input name="fullName" required value={contactDraft.fullName} onChange={(e) => setContactDraft((current: ContactDraft) => ({ ...current, fullName: e.target.value }))} /></label><label className="field-label">Mobile number<input name="mobileNumber" pattern="[0-9]{10}" required value={contactDraft.mobileNumber} onChange={(e) => setContactDraft((current: ContactDraft) => ({ ...current, mobileNumber: e.target.value }))} /></label><label className="field-label">Email address (optional)<input name="email" type="email" value={contactDraft.email} onChange={(e) => setContactDraft((current: ContactDraft) => ({ ...current, email: e.target.value }))} /></label><label className="field-label">Simulated OTP<input name="otp" inputMode="numeric" required value={contactDraft.otp} onChange={(e) => setContactDraft((current: ContactDraft) => ({ ...current, otp: e.target.value }))} /></label></div><div className="dashboard-actions"><button className="secondary-button dashboard-secondary" type="button" onClick={() => setStep("evidence")}>Back</button><button className="primary-button dashboard-primary" disabled={loading}>Verify and continue</button></div></form>;
  if (step === "review") return <section className="journey-card screen"><p className="eyebrow">Step 6</p><h1>Review complaint</h1><Review caseData={caseData} /><label className="declaration"><input type="checkbox" checked={declaration} onChange={(e) => setDeclaration(e.target.checked)} /> I confirm that the information provided above is true to the best of my knowledge.</label><div className="notice disclaimer-box">This is an independent hackathon prototype. No complaint will be sent to any government authority.</div><div className="dashboard-actions"><button className="secondary-button dashboard-secondary" type="button" onClick={() => setStep("contact")}>Back</button><button className="primary-button dashboard-primary" onClick={submit} disabled={loading || !declaration}>Submit Demo Complaint</button></div></section>;
  return <section className="journey-card screen submission-success"><h1>Complaint submitted successfully</h1><p className="lead">Your complaint has been recorded in this demonstration system.</p><div className="submission-metadata-card"><strong>Demo Reference Number</strong><h2>{caseData.mockSubmission?.reference}</h2><p>{caseData.mockSubmission?.submittedAt && new Date(caseData.mockSubmission.submittedAt).toLocaleString()}</p></div><div className="notice caution-box">This is a simulated submission. No information was sent to the National Cyber Crime Reporting Portal or any government authority.</div>{!user && pendingClaimToken && <div className="notice"><strong>Create an account or sign in to save and track this complaint</strong><p>Your complaint reference will still work without an account. Signing in now attaches this submitted demo complaint to your citizen dashboard.</p><div className="dashboard-actions"><button className="primary-button dashboard-primary" onClick={() => go("signup")}>Create an account</button><button className="secondary-button dashboard-secondary" onClick={() => go("login")}>Sign in</button></div></div>}<div className="dashboard-actions"><button className="primary-button dashboard-primary" onClick={() => caseData.mockSubmission?.reference && openTrack(caseData.mockSubmission.reference)}>Track this Complaint</button><button className="secondary-button dashboard-secondary" onClick={() => go("home")}>Return Home</button><button className="secondary-button dashboard-secondary" onClick={begin}>Register Another Complaint</button></div></section>;
}

function Review({ caseData }: { caseData: IncidentCase }) { const i = caseData.incident; return <div className="review-sections"><section><h2>Complaint Type</h2><p>Financial Fraud · UPI</p></section><section><h2>Incident Details</h2><p>Date: {i.incidentDate ?? "Not provided"} · Amount: {i.amountLost ?? "Not provided"}</p><p>Payment app: {i.paymentApp ?? "Not provided"} · Transaction ID: {i.transactionId ?? "Not provided"}</p></section><section><h2>Description</h2><p>{caseData.story}</p></section><section><h2>Payment/Suspect Details</h2><p>UPI ID: {i.recipientUpiId ?? "Not provided"}</p></section><section><h2>Evidence</h2><p>{caseData.evidence.length ? caseData.evidence.map((x) => x.filename).join(", ") : "No evidence added"}</p></section><section><h2>Contact Details</h2><p>{caseData.contact?.fullName} · {caseData.contact?.mobileNumber} · {caseData.contact?.email ?? "No email"}</p></section></div>; }

function Track({ initialReference }: { initialReference: string }) {
  const [reference, setReference] = useState(initialReference);
  const [result, setResult] = useState<any>(null);
  const [error, setError] = useState("");
  const checkReference = async (value: string) => { setError(""); try { setResult(await caseApi.track(value)); } catch (x) { setResult(null); setError(x instanceof Error ? x.message : "Unable to check status."); } };
  const check = async (e: FormEvent) => { e.preventDefault(); await checkReference(reference); };
  useEffect(() => { setReference(initialReference); if (initialReference) void checkReference(initialReference); }, [initialReference]);
  return <section className="content-page"><h1>Track Complaint</h1><p>Local demonstration tracking only.</p><form onSubmit={check} className="inline-form"><label>Complaint Reference Number<input value={reference} onChange={(e) => setReference(e.target.value)} required /></label><button className="primary-button">Check Status</button></form>{error && <p className="notice error">{error}</p>}{result && <div className="timeline"><p>✓ Complaint Submitted <small>{new Date(result.submittedAt).toLocaleString()}</small></p><p>✓ Complaint received <small>{new Date(result.submittedAt).toLocaleString()}</small></p><p>● Initial Review <small>Complaint information recorded in the demonstration system.</small></p><p>○ Assigned for Review <small>Awaiting demonstration workflow</small></p><p>○ Further Action</p><p className="notice">Demo status — this prototype is not connected to the government complaint tracking system.</p></div>}</section>;
}

function Login({ onLogin, go }: { onLogin: (user: SafeUser) => Promise<void>; go: (page: Page) => void }) {
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); setLoading(true); setMessage(""); try { const result = await caseApi.login({ email, password }); await onLogin(result.user); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to sign in."); } finally { setLoading(false); } };
  return <form className="content-page auth-page" onSubmit={submit}><p className="eyebrow">Citizen account</p><h1>Login</h1><p className="notice">Demo prototype: use synthetic account information only.</p>{message && <p className="notice error">{message}</p>}<label>Email<input type="email" value={email} onChange={(e) => setEmail(e.target.value)} required /></label><label>Password<input type="password" value={password} onChange={(e) => setPassword(e.target.value)} required /></label><div className="dashboard-actions"><button className="secondary-button dashboard-secondary" type="button" onClick={() => go("home")}>Back</button><button className="primary-button dashboard-primary" disabled={loading}>Login</button><button className="secondary-button dashboard-secondary" type="button" onClick={() => go("signup")}>Create an account</button></div></form>;
}

function Signup({ onSignup, go }: { onSignup: (user: SafeUser) => Promise<void>; go: (page: Page) => void }) {
  const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); setMessage(""); if (password.length < 8) return setMessage("Password must be at least 8 characters."); if (password !== confirm) return setMessage("Passwords do not match."); setLoading(true); try { const result = await caseApi.register({ name, email, password }); await onSignup(result.user); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to create account."); } finally { setLoading(false); } };
  return <form className="content-page auth-page" onSubmit={submit}><p className="eyebrow">Citizen account</p><h1>Create an account</h1><p className="notice">Demo prototype: use synthetic account information only.</p>{message && <p className="notice error">{message}</p>}<label>Full name<input value={name} onChange={(e) => setName(e.target.value)} required /></label><label>Email<input type="email" value={email} onChange={(e) => setEmail(e.target.value)} required /></label><label>Password<input type="password" value={password} onChange={(e) => setPassword(e.target.value)} minLength={8} required /></label><label>Confirm password<input type="password" value={confirm} onChange={(e) => setConfirm(e.target.value)} minLength={8} required /></label><div className="dashboard-actions"><button className="secondary-button dashboard-secondary" type="button" onClick={() => go("home")}>Back</button><button className="primary-button dashboard-primary" disabled={loading}>Create account</button><button className="secondary-button dashboard-secondary" type="button" onClick={() => go("login")}>Sign in</button></div></form>;
}

function Suspect() { const [identifier, setIdentifier] = useState(""), [lookup, setLookup] = useState(""), [confirmation, setConfirmation] = useState(""); const check = async (e: FormEvent) => { e.preventDefault(); const item = await caseApi.checkSuspect(identifier); setLookup(item.label); }; const report = async (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); const form = new FormData(e.currentTarget); const item = await caseApi.reportSuspect({ type: String(form.get("type")), identifier: String(form.get("identifier")), description: String(form.get("description")) }); setConfirmation(item.reference); }; return <section className="content-page"><h1>Check or Report a Suspect</h1><div className="two-column"><form onSubmit={check}><h2>Check a Suspect</h2><p>Synthetic demonstration data — not a real government database.</p><label>Identifier<input value={identifier} onChange={(e) => setIdentifier(e.target.value)} placeholder="Mobile, email, UPI ID, URL or bank account" required /></label><button className="primary-button">Check identifier</button>{lookup && <p className="notice">{lookup}</p>}</form><form onSubmit={report}><h2>Report a Suspect</h2><label>Identifier type<select name="type"><option>UPI ID</option><option>Mobile number</option><option>Email</option><option>Website / URL</option><option>Bank account</option></select></label><label>Identifier<input name="identifier" required /></label><label>Description<textarea name="description" rows={4} required /></label><button className="primary-button">Save demo report</button>{confirmation && <p className="notice">Saved locally. Reference: <strong>{confirmation}</strong></p>}</form></div></section>; }
function Resources() { return <section className="content-page"><h1>Resources</h1><div className="service-grid"><article className="service-card"><strong>Cyber Safety Tips</strong><span>Never share OTPs, PINs, passwords, or remote-access permissions.</span></article><article className="service-card"><strong>Citizen Manual</strong><span>Keep dates, amounts, transaction IDs, and screenshots available.</span></article><article className="service-card"><strong>Cyber Awareness</strong><span>Verify unexpected calls and messages through official channels.</span></article><article className="service-card"><strong>Common Scam Types</strong><span>KYC calls, payment requests, fake support, and investment schemes.</span></article><article className="service-card"><strong>What To Do After Financial Fraud</strong><span>Contact your bank or payment provider promptly and use official support channels.</span></article></div><div className="help-section"><div><strong>Cyber Crime Helpline</strong><p>1930</p></div><div><strong>Police Emergency</strong><p>112</p></div></div><section className="information-section"><h2>Future AI-assisted enhancements</h2><p>AI could later help with voice-to-text, organising text into complaint details, reading screenshot or document details, multilingual assistance, and complaint draft generation. AI assists the citizen; it does not decide whether a crime occurred, determine guilt, or submit complaints automatically.</p></section></section>; }
function Faq() { const items = [["What is the National Cyber Crime Reporting Portal?","This independent prototype is inspired by citizen cybercrime reporting services; it is not an official government website."],["What information should I keep ready?","Transaction details, dates, amounts, communication records, and any screenshots."],["What should I do after UPI fraud?","Contact your bank or payment provider promptly and use official support channels."],["Can I report without evidence?","Yes. Evidence is optional in this prototype."],["What is a transaction ID/UTR?","It is the reference issued for a payment transaction by the payment service or bank."],["What is the 1930 helpline?","It is the cybercrime financial-fraud helpline number published for official assistance."],["Can I track a complaint?","Demo complaints can be tracked locally with their generated reference number."],["What happens after submitting a complaint?","This prototype stores a local demo record only. Real complaint handling is not implemented in this prototype."]]; return <section className="content-page"><h1>Frequently asked questions</h1>{items.map(([q,a]) => <details className="faq" key={q}><summary>{q}</summary><p>{a}</p></details>)}</section>; }
function Contact() { return <section className="content-page"><h1>Help &amp; Contact</h1><div className="help-section"><div><strong>Cyber Crime Helpline</strong><p>1930</p></div><div><strong>Police Emergency</strong><p>112</p></div></div><p>For the official National Cyber Crime Reporting Portal, visit <a href="https://www.cybercrime.gov.in/" target="_blank" rel="noreferrer">cybercrime.gov.in</a>.</p><p>This website is an independent hackathon prototype and is not connected to the official portal.</p></section>; }
function Policies() { return <section className="content-page"><h1>Privacy, accessibility &amp; website policies</h1><h2>Privacy Notice</h2><p>Use synthetic data only. Demo records are stored locally for this prototype.</p><h2>Disclaimer</h2><p>Independent hackathon prototype; not a government website; not connected to NCRP/I4C; no real complaint is submitted; and the current prototype does not use AI.</p><h2>Accessibility</h2><p>The portal uses semantic controls, keyboard focus styles, readable contrast, and responsive layouts.</p><h2>Website Policies</h2><p>This demo provides general information only and makes no legal, investigative, or recovery claims.</p></section>; }
