export type Incident = { fraudType: "upi_financial_fraud"; incidentDate: string | null; incidentTime: string | null; amountLost: number | null; currency: "INR"; paymentApp: string | null; transactionId: string | null; recipientUpiId: string | null; victimName: string | null; victimContact: string | null; phoneNumber: string | null; bankOrMerchant: string | null; narrativeFacts: string[] };
export type IncidentField = "incidentDate" | "amountLost" | "paymentApp" | "transactionId" | "recipientUpiId";
export type Evidence = { id: string; filename: string; mimeType: "image/png" | "image/jpeg" | "application/pdf"; storedPath: string; size: number };
export type ContactDetails = { fullName: string; mobileNumber: string; email: string | null; otpVerified: boolean };
export type IncidentCase = { id: string; status: string; story: string; incident: Incident; verifiedFields: string[]; missingFields: IncidentField[]; evidence: Evidence[]; contact: ContactDetails | null; mockSubmission: { submittedAt: string; reference: string; status: "Complaint Submitted" } | null; userId: string | null; claimToken?: string };
export type SafeUser = { id: string; name: string; email: string; createdAt: string };
export type MissingDetails = { missingFields: IncidentField[]; nextQuestion: { field: IncidentField; question: string } | null };
async function request<T>(path: string, options?: RequestInit): Promise<T> { const response = await fetch(`/api${path}`, { credentials: "include", ...options, headers: { "Content-Type": "application/json", ...options?.headers } }); if (!response.ok) { const body = await response.json().catch(() => null) as { error?: string } | null; throw new Error(body?.error ?? "Something went wrong. Please try again."); } return response.json() as Promise<T>; }
export const caseApi = {
  create: () => request<IncidentCase>("/cases", { method: "POST", body: "{}" }), saveStory: (id: string, story: string) => request<IncidentCase>(`/cases/${id}/story`, { method: "POST", body: JSON.stringify({ story }) }),
  updateIncident: (id: string, updates: Partial<Omit<Incident, "fraudType" | "currency">>) => request<IncidentCase>(`/cases/${id}/incident`, { method: "PATCH", body: JSON.stringify(updates) }), getMissing: (id: string) => request<MissingDetails>(`/cases/${id}/missing`),
  uploadEvidence: (id: string, filename: string, mimeType: Evidence["mimeType"], base64: string) => request<IncidentCase>(`/cases/${id}/evidence`, { method: "POST", body: JSON.stringify({ filename, mimeType, base64 }) }), removeEvidence: (id: string, evidenceId: string) => request<IncidentCase>(`/cases/${id}/evidence/${evidenceId}`, { method: "DELETE" }),
  saveContact: (id: string, contact: ContactDetails) => request<IncidentCase>(`/cases/${id}/contact`, { method: "PATCH", body: JSON.stringify(contact) }), submitMock: (id: string) => request<IncidentCase>(`/cases/${id}/mock-submit`, { method: "POST" }),
  track: (reference: string) => request<{ reference: string; submittedAt: string; status: string; caseId: string }>(`/track/${encodeURIComponent(reference)}`), checkSuspect: (identifier: string) => request<{ found: boolean; label: string }>(`/suspects/check?identifier=${encodeURIComponent(identifier)}`), reportSuspect: (data: { type: string; identifier: string; description: string }) => request<{ reference: string }>("/suspects", { method: "POST", body: JSON.stringify(data) }),
  me: () => request<{ user: SafeUser }>("/auth/me"), register: (data: { name: string; email: string; password: string }) => request<{ user: SafeUser }>("/auth/register", { method: "POST", body: JSON.stringify(data) }), login: (data: { email: string; password: string }) => request<{ user: SafeUser }>("/auth/login", { method: "POST", body: JSON.stringify(data) }), logout: () => request<{ ok: boolean }>("/auth/logout", { method: "POST" }),
  myCases: () => request<IncidentCase[]>("/me/cases"), claimCase: (claimToken: string) => request<IncidentCase>("/me/cases/claim", { method: "POST", body: JSON.stringify({ claimToken }) }),
};
